name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test,dev]
      shell: micromamba-shell {0}
    - name: Test with pytest
      run: |
        pytest
      shell: micromamba-shell {0}
          